plates_small = Item.create(name: "Plates-Small",)
spoon = Item.create(name: "Spoon")
fork = Item.create(name: "Fork")
Inventory.create(item_id: plates_small.id, par: 50, on_hand: 60)
Inventory.create(item_id: spoon.id, par: 50, on_hand: 30)
Inventory.create(item_id: fork.id, par: 100, on_hand: 102)
